### ISSUE TITLE
Fails on various JVMs

### ISSUE THREAD

**Issue by bmarwell** [dev-aspectj/aspectj-maven-plugin#7]
Hi,

either aspectj OR this plugin (don't know) is not java compliant.

https://github.com/apache/shiro/pull/301/checks?check_run_id=2685544353

```
Caused by: java.io.IOException: /opt/hostedtoolcache/java_adopt-openj9_jdk/11.0.11-9/x64/lib/jrt-fs.jar not exist
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:118)
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
	at org.aspectj.weaver.bcel.ClassPathManager$JImageEntry.<init>(ClassPathManager.java:360)
	... 33 more
```

Happens only on 4 linux JVMs:
* 11 adopt openj9
* 11 zulu
* 16 adopt hotspot
* 16 adopt openj9
* 16 zulu

**Comment by bmarwell** [comment]
Funny, does NOT fail on the ASF jenkins though… https://ci-builds.apache.org/blue/organizations/jenkins/Shiro%2FShiro-all/detail/PR-301/8/pipeline

**Comment by bmarwell** [comment]
I created https://github.com/actions/setup-java/issues/183 because I now believe it is a github problem.

**Comment by kriegaex** [comment]
So can we close this here?

**Comment by kriegaex** [comment]
I am closing the issue, which seems to be unrelated to this plugin. Feel free to reopen, if you there is other evidence. Thank you.
